### ISSUE TITLE
Question: User Permissions?

### ISSUE THREAD

**Issue by edlins** [ryanblenis/MeshCentral-ScriptTask#10]
I have just setup a user account that can only view the Desktop because I don't trust them.  However, the Plugins tab appears on their device view and it seems to allow them to upload and execute scripts.  Is there a way to disable the plugin for this user?

**Comment by edlins** [comment]
I may have answered my own question.  When I setup a user as view-only (Server Permissions: No New Device Groups, No Tools; Device Group Permissions: Remote Control, Remote View Only, No Terminal Access, No File Access, No Intel AMT) the user can Upload and make New ScriptTasks but can't run them.  When I set Server Files limit to 0k, the user can no longer Upload and make New ScriptTasks.  I don't know exactly which permission prevents them from executing the scripts, but this is good enough for my purposes.

**Comment by ryanblenis** [comment]
Ah, perfect. I think there's got to be a better permission system in place. Right now it's all on each plugin to implement, but would be nice if they could have a standard format that MC honors. I started working on this a bit, but it is a bit involved. Glad you've got something working for your purposes here.
