### ISSUE TITLE
Plugin not working, MeshCentral 0.8.36/37

### ISSUE THREAD

**Issue by I2700I** [ryanblenis/MeshCentral-ScriptTask#12]
Please see the image https://i.imgur.com/ShOizFd.png
The Event Viewer plugin is clickable and works, however the ScriptTask does not appear to be a working link. Tested in multiple browsers, does not appear to be a browser issue. No errors in the server log.

Thanks.

**Comment by ryanblenis** [comment]
The event viewer plugin has admin settings, which is why it is a link on the My Server -> Plugins page. ScriptTask does not have any settings there, so it does not have a link. Take a look at a device -> Plugins -> ScriptTask to see the plugin.

**Comment by I2700I** [comment]
Thanks, that was not obvious (at least to me).
