### ISSUE TITLE
Plugins not working in New Meshcentral version

### ISSUE THREAD

**Issue by pggsadmin** [ryanblenis/MeshCentral-ScriptTask#17]
In the latest mesh central version. The Plugins not working its causes server disconnection during installation

**Comment by pggsadmin** [comment]
Seems its my config issues

**Comment by itsmedakshesh** [comment]
> Seems its my config issues

What did you do? I have the same issue if you can help me. Thank you.

**Comment by VINISHVV** [comment]
> > Seems its my config issues
> 
> What did you do? I have the same issue if you can help me. Thank you.

I just uninstall all plugin and disable the plugin from config.js and restart server

Then again i activate plugin and install the requires plugins
