### ISSUE TITLE
Installation failing with "value not defined" error

### ISSUE THREAD

**Issue by mikecole79** [ryanblenis/MeshCentral-ScriptTask#19]
I'm not too sure this is actually a plug-in issue.  I suspect there's some oddity of my configuration that isn't working quite right, but if anyone can give me a hint as to what that might be, it would be greatly appreciated.  

Thanks!

**Comment by ryanblenis** [comment]
Going to need a bit more information than that (server version, node version, error message context, etc). Note that I've just submitted a patch for MC ( https://github.com/Ylianst/MeshCentral/pull/3143 ) for plugin install / removal in general. All plugins will need to be updated once that is approved.

**Comment by mikecole79** [comment]
1. Navigate to My Server > Plugins 
2. Click on "Download Plugin" button
3. Paste in URL from install instructions "https://raw.githubusercontent.com/ryanblenis/MeshCentral-ScriptTask/master/config.json"
4. Click "Ok"

![image](https://user-images.githubusercontent.com/6404936/136150494-1f6be912-5599-4fe4-969f-c98122695e94.png)


Server version 0.9.28

 Download console text
> versions
{
    "http_parser": "2.9.3",
    "node": "10.19.0",
    "v8": "6.8.275.32-node.55",
    "uv": "1.34.2",
    "zlib": "1.2.11",
    "brotli": "1.0.7",
    "ares": "1.15.0",
    "modules": "64",
    "nghttp2": "1.40.0",
    "napi": "5",
    "openssl": "1.1.1d",
    "icu": "66.1",
    "unicode": "13.0",
    "cldr": "36.1",
    "tz": "2021a"
}

**Comment by ryanblenis** [comment]
Again, please see https://github.com/Ylianst/MeshCentral/pull/3143 that we're waiting on submission into the main project to fix this.

**Comment by mikecole79** [comment]
Updated to 0.9.29.  Problem persists.
