### ISSUE TITLE
no longer working after mesh v0.9.19

### ISSUE THREAD

**Issue by smartekIT** [ryanblenis/MeshCentral-ScriptTask#20]
Hi,
found out that after v0.9.19 you can no longer use it or even enable/disable/remove.
had to remove it the hard way through mongodb commands and physically removing the folder.

after removing the plugin, i was shocked when i discovered that not only it wasn't working but it was blocking some enhancement done over the meshcentral updates, so now i start seeing those fixes working in meshcentral.

one of those was, don't show empty groups in the (my devices tab) until they have clients joined, but of course it's showing in the groups tab.. with this plugin installed it used to show them all (empty & non empty groups) under (my devices tab). well i have 50 empty groups but i need to keep them for clients connected when needed and different settings and notes for each group. it's neater to have them hidden from (my devices tab) page until they get clients. scripttask was affecting this feature so that page was a mess.

i think guys you need to review the whole code of this plugin as 100% it's not in working order anymore and affecting other features. it's been a long time since it was reviewed or updated. 

Thanks heaps for your hard work.

**Comment by pggsadmin** [comment]
@ryanblenis
Can you help to fix this?

**Comment by ryanblenis** [comment]
Hey guys, I've been working on other projects but I'll try to update my dev environment for MeshCentral and see what's going on with all the new changes as soon as I can. Thanks for the reports.

**Comment by pggsadmin** [comment]
@ryanblenis
This tool will helps to reduce minimum 30% of our workload. From last few days its stop working.

I hope you will look into this asap and suggest a fix.

Sorry for disturbing you during your busy time.

**Comment by Adminvvs** [comment]
@ryanblenis
Can you help here

**Comment by Adminvvs** [comment]
@ryanblenis any update

**Comment by ryanblenis** [comment]
Closed in lieu of previous reported issue #18
