### ISSUE TITLE
Bypass ExecutionPolicy

### ISSUE THREAD

**Issue by poiNt3D** [ryanblenis/MeshCentral-ScriptTask#28]
Hello. 
So i added a ps1 script and scheduled it. And got PSSecurityException. 
Seems like i need to set ExecutionPolicy on every machine that i would like to run scripts on.
ScriptTask could just do something like this:
powershell.exe  -executionpolicy bypass -file .\script.ps1

**Comment by SpookOz** [comment]
Hey. I got around this issue by running the "Group Action" / "Run Commands" in the main console, then running the command: `Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser`

This effectively gives the MeshCentral user the ability to bypass the Execution Policy *at all times*. I'm not sure how much of a security risk this poses, and I'd appreciate feedback. n my mind it seems acceptable, as it allows MC to run Ps scripts, but not other users. After that, PS scripts in ScriptTask run fine.

**Comment by ryanblenis** [comment]
Closed in PR #43
