### ISSUE TITLE
Cant get the plugin to install

### ISSUE THREAD

**Issue by aislerad** [ryanblenis/MeshCentral-ScriptTask#30]
Ryan,

Does this work with the latest version of meshcentral?

**Comment by cgb** [comment]
I've been using it successfully with Meshcentral up to 1.0.19.

1.0.31 is latest version and I haven't updated to it, but I suspect it will work fine there too...

**Comment by aislerad** [comment]
Ryan,

Getting the below error and when I click on the dropdown it tells me to delete or install try both and then get a popup about plugins being altered this may require agent core update.

***@***.***

**Comment by cgb** [comment]
Hey there, I can't see an error in your reply..

**Comment by aislerad** [comment]
Ryan,

Looks like I got it working now the folder it creates in the meshcentral-data directory didn't have permissions so it was failing to install.

Thanks,

**Comment by cgb** [comment]
Nice job..!

FYI, I'm not Ryan, just a fellow user of ScriptTask and MeshCentral ;)

You can mark this issue as closed now.
