### ISSUE TITLE
Installing plugin makes some agent go offline

### ISSUE THREAD

**Issue by canove** [ryanblenis/MeshCentral-ScriptTask#5]
Hello, 
Thanks for this. Scripting is a must have feature and you just make it work on MeshCentral.

I had some agents with Windows 7 x64 going offline when activating this. On affected agents, console shows:
```
uncaughtException1: Error: Error in Finalizer: [Invalid C function means you forgot to return 0]  => EventEmitter.emit(): Event dispatch for '~' on 'win-message-pump' threw an exception: EventEmitter.on(): Event 'exit' not found in method '()'
```

Its a bug?

**Comment by ryanblenis** [comment]
Hi @canove,

The win-message-pump is a module built into the [MeshAgent](https://github.com/Ylianst/MeshAgent/blob/981ee96ad7197423684279794a8f168178707e50/modules/win-message-pump.js). ScriptTask doesn't directly utilize it for anything, but if there's an association between installing ScriptTask and receiving the error I can certainly take a look.

I don't have any Win7 anymore (it went out of support by MS in January), but I might be able to spin up a test VM to see if it has an affect. What % of your Win7 machines did you see the issue on?

Did you select the option to update the cores after installing ScriptTask?

At what point in the install / usage did the issue occur? Do you have a way to repeat the behavior?

Also, what version of MeshCentral are you using?

**Comment by canove** [comment]
Hello @ryanblenis , thanks for the feedback.

**Comment by canove** [comment]
Hi @ryanblenis . I just tried it now, and it seems they all come back online after a while.

I have installed the plugin again and looked up on devices, it goes from 127 to 108 online. The offline ones are all Windows 7, but after a few moments all came back online again.

You can close this. Thanks.

**Comment by ryanblenis** [comment]
Thank you for the info! Sounds like the MeshAgent might fail/halt when a new core is sent. Could be an issue to raise with the MeshAgent side of the project, but since it's for Win7, which is no longer under support, and the agent restarts itself as the service failure directive states it should, probably not much to worry about here.

Thank you.
