### ISSUE TITLE
Unable to uninstall plugin

### ISSUE THREAD

**Issue by vish84** [ryanblenis/MeshCentral-ScriptTask#8]
Hi 

I have tried to uninstall the plugin, when from the action when I click delete, and confirm the prompt to delete. The server disconnects. When I log back in the plugin is still shown. 

I was trying to remove and install again to start afresh

**Comment by ryanblenis** [comment]
Hi @vish84 ,

Sorry to hear you're having issues, what server version are you on so I can try and replicate this for you?

**Comment by vish84** [comment]
Hey, i just realised i wrote the title wrong, should have been uninstall.

The server version is 0.5.73

**Comment by vish84** [comment]
Updated the server to 0.5.77 and tried again, this time I was able to uninstall.
